# Generated by Django 2.0.4 on 2018-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphHistory1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField()),
                ('game', models.PositiveIntegerField(default=0)),
                ('medal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GraphHistory2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveIntegerField()),
                ('game', models.PositiveIntegerField(default=0)),
                ('medal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.IntegerField(default=0)),
                ('medals', models.PositiveIntegerField(default=0, verbose_name='medals')),
                ('turbo2', models.PositiveIntegerField(default=0, verbose_name='turbo2')),
                ('deposit', models.BooleanField(default=False, verbose_name='deposit')),
            ],
        ),
        migrations.CreateModel(
            name='SlotMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=255)),
                ('game_count', models.IntegerField(default=0)),
                ('medal', models.IntegerField(default=0, verbose_name='medal')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='history',
            name='slot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.SlotMachine', verbose_name='slot_number'),
        ),
    ]
