# Generated by Django 2.0.4 on 2018-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphhistory1',
            name='player_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graphhistory2',
            name='player_history2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
