# Generated by Django 2.0.4 on 2018-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_game_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_medals',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='turbo_slot1',
            field=models.BooleanField(default=False, help_text='aaa'),
        ),
        migrations.AddField(
            model_name='user',
            name='turbo_slot2',
            field=models.BooleanField(default=False),
        ),
    ]
