# Generated by Django 2.1.3 on 2019-05-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20180603_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_medals',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
